eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.103:8762/eureka/
    register-with-eureka: false
  #测试环境关闭
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8762
